// <auto-generated />
using System;
using CairoGo.Models.DbContextApp;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CairoGo.Migrations
{
    [DbContext(typeof(CairoGoDbContext))]
    [Migration("20251123191204_removeTicketPricePropInPlace")]
    partial class removeTicketPricePropInPlace
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CairoGo.Models.Entity.ActivityType", b =>
                {
                    b.Property<Guid>("ActivityTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Name")
                        .HasColumnType("int");

                    b.HasKey("ActivityTypeId");

                    b.ToTable("ActivityTypes");
                });

            modelBuilder.Entity("CairoGo.Models.Entity.ExperimentAssignment", b =>
                {
                    b.Property<Guid>("AssignmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("ConversionSuccess")
                        .HasColumnType("bit");

                    b.Property<string>("ExperimentName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("PlacesClicked")
                        .HasColumnType("int");

                    b.Property<int?>("TripPlansGenerated")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("VariantName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("AssignmentId");

                    b.HasIndex("UserId", "ExperimentName")
                        .IsUnique();

                    b.ToTable("ExperimentAssignments");
                });

            modelBuilder.Entity("CairoGo.Models.Entity.Favorite", b =>
                {
                    b.Property<Guid>("FavoriteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("PlaceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UserCategory")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("FavoriteId");

                    b.HasIndex("PlaceId");

                    b.HasIndex("UserId", "CreatedAt");

                    b.HasIndex("UserId", "PlaceId")
                        .IsUnique();

                    b.ToTable("Favorites");
                });

            modelBuilder.Entity("CairoGo.Models.Entity.Interaction", b =>
                {
                    b.Property<Guid>("InteractionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContextJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("PlaceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("InteractionId");

                    b.HasIndex("PlaceId");

                    b.HasIndex("UserId");

                    b.ToTable("Interactions");
                });

            modelBuilder.Entity("CairoGo.Models.Entity.ModelVersion", b =>
                {
                    b.Property<Guid>("ModelVersionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<float?>("AverageCTR")
                        .HasColumnType("real");

                    b.Property<float?>("AverageConversion")
                        .HasColumnType("real");

                    b.Property<string>("ConfigJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DeployedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeprecatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("PredictionCount")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ModelVersionId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ModelVersions");
                });

            modelBuilder.Entity("CairoGo.Models.Entity.Place", b =>
                {
                    b.Property<Guid>("PlaceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AccessibilityInfo")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int?>("AvgVisitDurationMinutes")
                        .HasColumnType("int");

                    b.Property<int?>("BestTimeOfDay")
                        .HasColumnType("int");

                    b.Property<string>("BestTimeToVisit")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<int>("CostTier")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullDescription")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("IndoorOutdoor")
                        .HasColumnType("int");

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ParkingInfo")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<float?>("Rating")
                        .HasColumnType("real");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("VisitorsPerYear")
                        .HasColumnType("int");

                    b.Property<string>("Website")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("PlaceId");

                    b.HasIndex("Category");

                    b.HasIndex("District");

                    b.HasIndex("Name");

                    b.HasIndex("Latitude", "Longitude");

                    b.ToTable("Places");
                });

            modelBuilder.Entity("CairoGo.Models.Entity.PlaceOperatingHours", b =>
                {
                    b.Property<Guid>("PlaceOperatingHoursId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<TimeSpan?>("CloseTime")
                        .HasColumnType("time");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("int");

                    b.Property<bool>("IsClosed")
                        .HasColumnType("bit");

                    b.Property<TimeSpan?>("OpenTime")
                        .HasColumnType("time");

                    b.Property<Guid>("PlaceId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("PlaceOperatingHoursId");

                    b.HasIndex("PlaceId", "DayOfWeek")
                        .IsUnique();

                    b.ToTable("PlaceOperatingHours", t =>
                        {
                            t.HasCheckConstraint("CK_OperatingHours_ValidTime", "[IsClosed] = 1 OR ([OpenTime] IS NOT NULL AND [CloseTime] IS NOT NULL AND [OpenTime] < [CloseTime])");
                        });
                });

            modelBuilder.Entity("CairoGo.Models.Entity.PlaceVibeTag", b =>
                {
                    b.Property<Guid>("PlaceVibeTagId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PlaceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("PlaceVibeTagId");

                    b.HasIndex("PlaceId");

                    b.ToTable("PlaceVibeTags");
                });

            modelBuilder.Entity("CairoGo.Models.Entity.PreferenceProfile", b =>
                {
                    b.Property<Guid>("ProfileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Budget")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("LastQuizTakenAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("TravelVibe")
                        .HasColumnType("int");

                    b.Property<int>("TripDays")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("WeatherPref")
                        .HasColumnType("int");

                    b.HasKey("ProfileId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("PreferenceProfiles");
                });

            modelBuilder.Entity("CairoGo.Models.Entity.RecommendationLog", b =>
                {
                    b.Property<Guid>("RecommendationLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModelVersion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("ModelVersionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PlaceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("Score")
                        .HasColumnType("real");

                    b.Property<string>("ScoreBreakdownJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("TripPlanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("WasBooked")
                        .HasColumnType("bit");

                    b.Property<bool>("WasClicked")
                        .HasColumnType("bit");

                    b.Property<bool>("WasShown")
                        .HasColumnType("bit");

                    b.HasKey("RecommendationLogId");

                    b.HasIndex("ModelVersion");

                    b.HasIndex("ModelVersionId");

                    b.HasIndex("PlaceId");

                    b.HasIndex("TripPlanId");

                    b.HasIndex("UserId", "GeneratedAt");

                    b.ToTable("RecommendationLogs");
                });

            modelBuilder.Entity("CairoGo.Models.Entity.Review", b =>
                {
                    b.Property<Guid>("ReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Comment")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("HelpfulCount")
                        .HasColumnType("int");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("bit");

                    b.Property<string>("PhotosJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PlaceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("Rating")
                        .HasColumnType("real");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("VisitDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ReviewId");

                    b.HasIndex("PlaceId", "Rating");

                    b.HasIndex("UserId", "PlaceId")
                        .IsUnique();

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("CairoGo.Models.Entity.SearchSession", b =>
                {
                    b.Property<Guid>("SearchSessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ClickedPlaceIds")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ResultCount")
                        .HasColumnType("int");

                    b.Property<string>("SearchParamsJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SearchQuery")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("SelectedPosition")
                        .HasColumnType("int");

                    b.Property<TimeSpan?>("TimeToClick")
                        .HasColumnType("time");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("SearchSessionId");

                    b.HasIndex("UserId", "CreatedAt");

                    b.ToTable("SearchSessions");
                });

            modelBuilder.Entity("CairoGo.Models.Entity.TrendingTag", b =>
                {
                    b.Property<Guid>("TagId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("PeriodEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("PeriodStart")
                        .HasColumnType("datetime2");

                    b.Property<float>("Score")
                        .HasColumnType("real");

                    b.HasKey("TagId");

                    b.HasIndex("Name", "PeriodStart", "PeriodEnd")
                        .IsUnique();

                    b.ToTable("TrendingTags", t =>
                        {
                            t.HasCheckConstraint("CK_TrendingTag_ValidPeriod", "[PeriodStart] < [PeriodEnd]");
                        });
                });

            modelBuilder.Entity("CairoGo.Models.Entity.TripDay", b =>
                {
                    b.Property<Guid>("TripDayId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("DayNumber")
                        .HasColumnType("int");

                    b.Property<decimal?>("EstimatedDayCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("TripPlanId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("TripDayId");

                    b.HasIndex("TripPlanId", "DayNumber")
                        .IsUnique();

                    b.ToTable("TripDays", t =>
                        {
                            t.HasCheckConstraint("CK_TripDay_PositiveDayNumber", "[DayNumber] > 0");
                        });
                });

            modelBuilder.Entity("CairoGo.Models.Entity.TripPlan", b =>
                {
                    b.Property<Guid>("TripPlanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("AlignmentScore")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<decimal?>("EstimatedCostPerPersonPerDay")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("ParentPlanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("PreferenceProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ScoreBreakdownJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("TripDays")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("VariationNumber")
                        .HasColumnType("int");

                    b.HasKey("TripPlanId");

                    b.HasIndex("ParentPlanId");

                    b.HasIndex("PreferenceProfileId");

                    b.HasIndex("UserId", "CreatedAt");

                    b.ToTable("TripPlans");
                });

            modelBuilder.Entity("CairoGo.Models.Entity.TripSlot", b =>
                {
                    b.Property<Guid>("TripSlotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AlternatePlaceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<decimal?>("PerPersonCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("PlaceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SlotType")
                        .HasColumnType("int");

                    b.Property<Guid>("TripDayId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("TripSlotId");

                    b.HasIndex("AlternatePlaceId");

                    b.HasIndex("PlaceId");

                    b.HasIndex("TripDayId", "SlotType")
                        .IsUnique();

                    b.ToTable("TripSlots");
                });

            modelBuilder.Entity("CairoGo.Models.Entity.UserApplication", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("HomeCity")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("JoinDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("PreferredCurrency")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("ProfilePictureUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("CairoGo.Models.Entity.UserPreferenceSignal", b =>
                {
                    b.Property<Guid>("SignalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<int>("ObservationCount")
                        .HasColumnType("int");

                    b.Property<string>("SignalType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("Weight")
                        .HasColumnType("real");

                    b.HasKey("SignalId");

                    b.HasIndex("UserId", "SignalType");

                    b.HasIndex("UserId", "SignalType", "Key")
                        .IsUnique();

                    b.ToTable("UserPreferenceSignals");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("PlaceActivityTypes", b =>
                {
                    b.Property<Guid>("ActivityTypesActivityTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PlacesPlaceId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ActivityTypesActivityTypeId", "PlacesPlaceId");

                    b.HasIndex("PlacesPlaceId");

                    b.ToTable("PlaceActivityTypes");
                });

            modelBuilder.Entity("PlaceTrendingTags", b =>
                {
                    b.Property<Guid>("PlacesPlaceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TrendingTagsTagId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("PlacesPlaceId", "TrendingTagsTagId");

                    b.HasIndex("TrendingTagsTagId");

                    b.ToTable("PlaceTrendingTags");
                });

            modelBuilder.Entity("PreferenceActivityTypes", b =>
                {
                    b.Property<Guid>("ActivityTypesActivityTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PreferenceProfilesProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ActivityTypesActivityTypeId", "PreferenceProfilesProfileId");

                    b.HasIndex("PreferenceProfilesProfileId");

                    b.ToTable("PreferenceActivityTypes");
                });

            modelBuilder.Entity("CairoGo.Models.Entity.ExperimentAssignment", b =>
                {
                    b.HasOne("CairoGo.Models.Entity.UserApplication", "User")
                        .WithMany("ExperimentAssignments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CairoGo.Models.Entity.Favorite", b =>
                {
                    b.HasOne("CairoGo.Models.Entity.Place", "Place")
                        .WithMany("Favorites")
                        .HasForeignKey("PlaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CairoGo.Models.Entity.UserApplication", "User")
                        .WithMany("Favorites")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Place");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CairoGo.Models.Entity.Interaction", b =>
                {
                    b.HasOne("CairoGo.Models.Entity.Place", "Place")
                        .WithMany("Interactions")
                        .HasForeignKey("PlaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CairoGo.Models.Entity.UserApplication", "User")
                        .WithMany("Interactions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Place");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CairoGo.Models.Entity.PlaceOperatingHours", b =>
                {
                    b.HasOne("CairoGo.Models.Entity.Place", "Place")
                        .WithMany("OperatingHours")
                        .HasForeignKey("PlaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Place");
                });

            modelBuilder.Entity("CairoGo.Models.Entity.PlaceVibeTag", b =>
                {
                    b.HasOne("CairoGo.Models.Entity.Place", "Place")
                        .WithMany("VibeTags")
                        .HasForeignKey("PlaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Place");
                });

            modelBuilder.Entity("CairoGo.Models.Entity.PreferenceProfile", b =>
                {
                    b.HasOne("CairoGo.Models.Entity.UserApplication", "User")
                        .WithOne("PreferenceProfile")
                        .HasForeignKey("CairoGo.Models.Entity.PreferenceProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CairoGo.Models.Entity.RecommendationLog", b =>
                {
                    b.HasOne("CairoGo.Models.Entity.ModelVersion", null)
                        .WithMany("RecommendationLogs")
                        .HasForeignKey("ModelVersionId");

                    b.HasOne("CairoGo.Models.Entity.Place", "Place")
                        .WithMany("RecommendationLogs")
                        .HasForeignKey("PlaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CairoGo.Models.Entity.TripPlan", "TripPlan")
                        .WithMany("RecommendationLogs")
                        .HasForeignKey("TripPlanId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CairoGo.Models.Entity.UserApplication", "User")
                        .WithMany("RecommendationLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Place");

                    b.Navigation("TripPlan");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CairoGo.Models.Entity.Review", b =>
                {
                    b.HasOne("CairoGo.Models.Entity.Place", "Place")
                        .WithMany("Reviews")
                        .HasForeignKey("PlaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CairoGo.Models.Entity.UserApplication", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Place");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CairoGo.Models.Entity.SearchSession", b =>
                {
                    b.HasOne("CairoGo.Models.Entity.UserApplication", "User")
                        .WithMany("SearchSessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("CairoGo.Models.Entity.TripDay", b =>
                {
                    b.HasOne("CairoGo.Models.Entity.TripPlan", "TripPlan")
                        .WithMany("TripDaysCollection")
                        .HasForeignKey("TripPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TripPlan");
                });

            modelBuilder.Entity("CairoGo.Models.Entity.TripPlan", b =>
                {
                    b.HasOne("CairoGo.Models.Entity.TripPlan", "ParentPlan")
                        .WithMany("AlternativePlans")
                        .HasForeignKey("ParentPlanId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CairoGo.Models.Entity.PreferenceProfile", "PreferenceProfile")
                        .WithMany()
                        .HasForeignKey("PreferenceProfileId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CairoGo.Models.Entity.UserApplication", "User")
                        .WithMany("TripPlans")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ParentPlan");

                    b.Navigation("PreferenceProfile");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CairoGo.Models.Entity.TripSlot", b =>
                {
                    b.HasOne("CairoGo.Models.Entity.Place", "AlternatePlace")
                        .WithMany("AlternateTripSlots")
                        .HasForeignKey("AlternatePlaceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CairoGo.Models.Entity.Place", "Place")
                        .WithMany("TripSlots")
                        .HasForeignKey("PlaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CairoGo.Models.Entity.TripDay", "TripDay")
                        .WithMany("TripSlots")
                        .HasForeignKey("TripDayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AlternatePlace");

                    b.Navigation("Place");

                    b.Navigation("TripDay");
                });

            modelBuilder.Entity("CairoGo.Models.Entity.UserPreferenceSignal", b =>
                {
                    b.HasOne("CairoGo.Models.Entity.UserApplication", "User")
                        .WithMany("PreferenceSignals")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("CairoGo.Models.Entity.UserApplication", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("CairoGo.Models.Entity.UserApplication", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CairoGo.Models.Entity.UserApplication", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("CairoGo.Models.Entity.UserApplication", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PlaceActivityTypes", b =>
                {
                    b.HasOne("CairoGo.Models.Entity.ActivityType", null)
                        .WithMany()
                        .HasForeignKey("ActivityTypesActivityTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CairoGo.Models.Entity.Place", null)
                        .WithMany()
                        .HasForeignKey("PlacesPlaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PlaceTrendingTags", b =>
                {
                    b.HasOne("CairoGo.Models.Entity.Place", null)
                        .WithMany()
                        .HasForeignKey("PlacesPlaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CairoGo.Models.Entity.TrendingTag", null)
                        .WithMany()
                        .HasForeignKey("TrendingTagsTagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PreferenceActivityTypes", b =>
                {
                    b.HasOne("CairoGo.Models.Entity.ActivityType", null)
                        .WithMany()
                        .HasForeignKey("ActivityTypesActivityTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CairoGo.Models.Entity.PreferenceProfile", null)
                        .WithMany()
                        .HasForeignKey("PreferenceProfilesProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CairoGo.Models.Entity.ModelVersion", b =>
                {
                    b.Navigation("RecommendationLogs");
                });

            modelBuilder.Entity("CairoGo.Models.Entity.Place", b =>
                {
                    b.Navigation("AlternateTripSlots");

                    b.Navigation("Favorites");

                    b.Navigation("Interactions");

                    b.Navigation("OperatingHours");

                    b.Navigation("RecommendationLogs");

                    b.Navigation("Reviews");

                    b.Navigation("TripSlots");

                    b.Navigation("VibeTags");
                });

            modelBuilder.Entity("CairoGo.Models.Entity.TripDay", b =>
                {
                    b.Navigation("TripSlots");
                });

            modelBuilder.Entity("CairoGo.Models.Entity.TripPlan", b =>
                {
                    b.Navigation("AlternativePlans");

                    b.Navigation("RecommendationLogs");

                    b.Navigation("TripDaysCollection");
                });

            modelBuilder.Entity("CairoGo.Models.Entity.UserApplication", b =>
                {
                    b.Navigation("ExperimentAssignments");

                    b.Navigation("Favorites");

                    b.Navigation("Interactions");

                    b.Navigation("PreferenceProfile");

                    b.Navigation("PreferenceSignals");

                    b.Navigation("RecommendationLogs");

                    b.Navigation("Reviews");

                    b.Navigation("SearchSessions");

                    b.Navigation("TripPlans");
                });
#pragma warning restore 612, 618
        }
    }
}
